"use client";

import type { Metadata } from "next";
import { Provider as ReduxProvider } from "react-redux";
import store from "@/store";
import { ChakraProvider } from "@chakra-ui/react";
import { QueryClient, QueryClientProvider } from "react-query";
import theme from "@/app/theme";
import { useState } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Provider({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [queryClient] = useState(() => new QueryClient());
  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
          <ReduxProvider store={store}>
            <ChakraProvider
            //  theme={theme}
            >
              {children}
            </ChakraProvider>
          </ReduxProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
